### ISSUE TITLE
On implementiation

### ISSUE THREAD

**Issue by Roxin92** [DushyantMainwal/RoundedImageView-Library#1]
Android resource compilation failed
Output:  C:\Users\ROXIN'X-THINKSPACE\AndroidStudioProjects\Clinic\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1458: error: duplicate value for resource 'attr/cornerRadius' with config ''.
C:\Users\ROXIN'X-THINKSPACE\AndroidStudioProjects\Clinic\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1458: error: resource previously defined here.

Command: C:\Users\ROXIN'X-THINKSPACE\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ce423f3549b05ab79b42c1766eeaee7e\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        C:\Users\ROXIN'X-THINKSPACE\AndroidStudioProjects\Clinic\app\build\intermediates\res\merged\debug \
        C:\Users\ROXIN'X-THINKSPACE\AndroidStudioProjects\Clinic\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

**Comment by DushyantMainwal** [comment]
It's because there's another file (or dependency) that has same attribute with name cornerRadius.

Remove that file or import the library as a module and change the attr name 'cornerRadius' to something else.

**Comment by Roxin92** [comment]
Ok thanks dude will do that.
